language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t richardkhonan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true richardkhonan/docker-react npm run test
