FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
RUN npm install --save-dev web-vitals
RUN npm install --save-dev @testing-library/jest-dom
RUN npm install --save-dev @testing-library/react
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]